# This is a basic workflow to help you get started with Actions

name: CI

env:
  PROJECT_NAME: GitHub Actions
  PROJECT_SHA: aad

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job:
   runs-on: ubuntu-latest
   steps:
    - name: Test Basic step
      run: echo "Hello message"

  my_second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Second Job for Build
        run: |
          echo "Starting job for Build"
          echo "Job names Build for ${{ env.PROJECT_NAME }}"

  get_list_files:
    runs-on: ubuntu-latest
    steps:
      - name: List of folders
        run: ls -la

      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List of folders after checkout
        run: ls -la
